app = 'p45'
primary_region = 'waw'

[build]
  dockerfile = "Dockerfile"

[machines]
  min_machines_running = 1

[[services]]
  internal_port = 9000
  protocol = "udp"
  min_machines_running = 1

  [[services.ports]]
    port = 9000
